spring:
  application:
    name: mixs
  datasource:
    url: jdbc:postgresql://localhost:5433/mixs
    username: ${DB_USERNAME:seu_usuario_aqui}
    password: ${DB_PASSWORD:sua_senha_aqui}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client_id: sua_credencial
            client_secret: sua_credencial

app:
  discogs:
    base-url: https://api.discogs.com
    token: seu_token
